%YAML:1.0

#common parameters
imu: 1         
lidar: 1 

imu0_topic: "/imu0"
cam0_topic: "/cam0/image_raw"
cam1_topic: "/cam1/image_raw"
lidar0_topic: "/lidar/livox"

lidar0_calib: "/shared/SensorFusion/config/mulan/lidar0.yaml"

T_body_imu0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1.0, 0.0, 0.0, 0.0, 
          0.0, 1.0, 0.0, 0.0, 
          0.0, 0.0, 1.0, 0.0, 
          0.0, 0.0, 0.0, 1.0]

T_body_lidar0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1.0, 0.0, 0.0, 1.77, 
         0.0, 1.0, 0.0, 0.0, 
         0.0, 0.0, 1.0, -0.05, 
         0.0, 0.0, 0.0, 1.0]


camera_stereo:
  